name: webview
version: 0.0.4-dev
description: A web component for the chrome app webview element.
author: Ross Smith <ross.dart.lang@gmail.com>
homepage: https://github.com/rmsmith/webview
dependencies:
  browser: any
  js: 0.0.14
  web_ui: 0.3.0+1