name: webview
version: 0.0.1
description: A web component to wrap the chrome app webview element.
author: Ross Smith <ross.dart.lang@gmail.com>
dependencies:
  browser: 0.0.1
  js: 0.0.13
  web_ui: 0.2.11