name: webview
version: 0.0.4
description: A web component for the chrome app webview element.
author: Ross Smith <ross.dart.lang@gmail.com>
homepage: https://github.com/rmsmith/webview
dependencies:
  browser: '>=0.3.1+1 <1.0.0'
  js: '>=0.0.15 <1.0.0'
  web_ui: 0.3.0+1